### ISSUE TITLE
[Proposal] run a node for committee, distribute the GAS to all bNEO holders

### ISSUE THREAD

**Issue by dusmart** [neoburger/code#12]
> bNEO holders receive the optimized GAS reward in [NEO GOVERNANCE](https://neo.org/gov)

One advantage of NeoBurger is to earn optimized GAS reward. If we could vote our own node as a committe, then bNEO holders can earn more reward.

What's more, I believe that bNEO contributors have good experiences on NEO governance. They also have a lot of experience with different aspects of NEO. Some members have a well understanding of the native chain's risks and how to defend them. Some developed lots of NEO contracts and dAPPs before. There're also some reseachers worked on Microsoft Azure Cloud and Amazon Cloud before, they are skilled on running a stable and reliable node.

Therefore. Let us run a node and vote ourselvies as a committee.

Please use 👍 and 👎 to interact with this proposal.

**Comment by vang1ong7ang** [comment]
executed
